#version: '3.9'

services:
  cassandra:
    image: cassandra:5.0
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=RetailCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./retail-data-stream/src/main/resources/schema.cql:/docker-entrypoint-initdb.d/01-schema.cql:ro
      - ./retail-data-stream/src/main/resources/init-sample-data.cql:/docker-entrypoint-initdb.d/02-init-sample-data.cql:ro

    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  cassandra_data:
